/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package BalancedGroupings2

import kotlin.test.Test
import kotlin.test.assertEquals

class BalancedGroupingsTest {
    val classUnderTest = BalancedGroupingsProblem()

    @Test fun EmptyStringTest() {
        assertEquals(true, classUnderTest.isBalanced(""))
    }

    @Test fun UnmatchedPairingsTest() {
        assertEquals(false, classUnderTest.isBalanced("Today is kind of rainy (the weather was better yesterday"))
    }

    
}
