/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package BalancedGroupings2

import kotlin.test.Test
import kotlin.test.assertEquals

class BalancedGroupingsTest {
    val classUnderTest = BalancedGroupingsProblem()

    @Test fun EmptyStringTest() {
        assertEquals(true, classUnderTest.isBalanced(""))
    }

    @Test fun UnmatchedPairingsTest() {
        assertEquals(false, classUnderTest.isBalanced("Today is kind of rainy (the weather was better yesterday"))
    }

    @Test fun UnmatchedPairingsTestTwo() {
        assertEquals(false, classUnderTest.isBalanced("Today is kind of rainy )the weather was better yesterday"))
    }

    @Test fun MatchedPairingTest() {
        assertEquals(true, classUnderTest.isBalanced(" {a + b} "))
    }

    @Test fun MultipleGroupingsTest() {
        assertEquals(true, classUnderTest.isBalanced("{ -b + sqrt(b^2 + 4ac)/(2a) }"))
    }

    @Test fun MultipleUnmatchedGroupingsTest() {
        assertEquals(false, classUnderTest.isBalanced("{ -b + sqrt(b^2 + 4ac}/[2a] "))
    }
}
