/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package BalancedGroupings2

import kotlin.test.Test
import kotlin.test.assertEquals

class BalancedGroupingsTest {
    @Test fun EmptyStringTest() {
        val classUnderTest = BalancedGroupingsProblem()
        assertEquals(true, classUnderTest.isBalanced(""))
    }
}
