/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package BalancedGroupings2

class BalancedGroupingsProblem {
    fun isBalanced(sequence: String): Boolean {
        return true 
    }
}
